# This is a TOML document

[collections.users]

[groups.admin]
[groups.admin.rules.carte_blanche]
template = "any()"

[groups.default]
[groups.default.rules.read_aggregates]
template = "collection('aggregates').anyRead()"
[groups.default.rules.read_aggregates_daily]
template = "collection('aggregates_daily').anyRead()"
[groups.default.rules.read_aggregates_hourly]
template = "collection('aggregates_hourly').anyRead()"
[groups.default.rules.read_current_user]
template = "collection('users').find({id: userId()})"
[groups.default.rules.read_marketorders]
template = "collection('orders').anyRead()"
[groups.default.rules.read_notifications]
template = "collection('notifications').anyRead()"
[groups.default.rules.read_portfolios]
template = "collection('portfolios').anyRead()"
[groups.default.rules.read_profit_alltime]
template = "collection('profit_alltime').anyRead()"
[groups.default.rules.read_profit_chart]
template = "collection('profit_chart').anyRead()"
[groups.default.rules.read_profit_top_items]
template = "collection('profit_top_items').anyRead()"
[groups.default.rules.read_profit_transactions]
template = "collection('profit_transactions').anyRead()"
[groups.default.rules.read_settings]
template = "collection('user_settings').anyRead()"
[groups.default.rules.read_subscription]
template = "collection('subscription').anyRead()"
[groups.default.rules.read_user_orders]
template = "collection('user_orders').anyRead()"
[groups.default.rules.write_notifications]
template = "collection('notifications').anyWrite()"
[groups.default.rules.write_settings]
template = "collection('user_settings').anyWrite()"
